
import matplotlib.pyplot as plt

def read_data(filename):
    x_values = []
    y_values = []
    with open(filename, 'r') as file:
        for line in file:
            parts = line.split(',')
            x = float(parts[0].split(':')[1].strip())
            y = float(parts[1].split(':')[1].strip())
            x_values.append(x)
            y_values.append(y)
    return x_values, y_values

# Read data from the files generated by the C programs
x_3rd, y_3rd = read_data('sin_approx_3rd.txt')
x_5th, y_5th = read_data('sin_approx_5th.txt')

# Generate the graph
plt.figure(figsize=(10, 6))
plt.plot(x_3rd, y_3rd, label='3rd Order McLaughlin', linewidth=2)
plt.plot(x_5th, y_5th, label='5th Order McLaughlin', linewidth=2)
plt.plot(x_3rd, [0]*len(x_3rd), linestyle='--', label='y = 0', color='black')

# Adding labels and legend
plt.xlabel('x', fontsize=14)
plt.ylabel('y', fontsize=14)
plt.title('Graph of McLaughlin Approximations (Output from C Programs)', fontsize=16)
plt.legend()
plt.grid(True)

# Display the plot
plt.show()
